apiVersion : apps/v1
kind: Deployment
metadata:
  name: mukeshsamplecloudtest 
  spec:    
    replicas: 1
    selector:
        matchLabels:
        app: authors
        version: v1
    template:
     metadata:
      labels:
        app: mukeshsamplecloudtest 
    spec:
      containers:
        - name: mukeshsamplecloudtest 
          image: democoreappazregistry.azurecr.io/mukeshsamplecloudtest
          ports:
          - containerPort: 80